#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@class TrailPoint;

/**
 * A representation of a single trail. A trail includes:
 *
 *  - A large number of trail points (defining the trail's route)
 *  - One (or a few) trail head(s), defining start/end points for the trail
 *  - A name
 *
 * Trail objects are primarily generated by the DataParser, but may be
 * instantiated separately.
 */
@interface Trail : NSObject {

@private
    NSString *_name;
    NSMutableArray *_trailPoints;
    NSMutableArray *_trailHeads;
    UIColor *_trailPaint;
}

/**
 * The name of this trail.
 */
@property (nonatomic, retain) NSString *name;

/**
 * The set of TrailPoint objects which make up this trail's path. Used to
 * draw the trail onto a map.
 */
@property (nonatomic, retain) NSMutableArray *trailPoints;

/**
 * The set of TrailPoint objects which, in addition to defining the trail's
 * path, act as start points, end points, or waypoints along the trail. Used
 * to define annotations on a map with more information.
 */
@property (nonatomic, retain) NSMutableArray *trailHeads;

/**
 * The color to paint the trail.
 */
@property (nonatomic, retain) UIColor *trailPaint;

/**
 * Create a new trail with the specified name.
 */
- (id)initWithName:(NSString *)name;

/**
 * Add a new point to this trail. This method handles the definition of a
 * "trail head" automatically and adds the point to the trailHeads list
 * automatically.
 */
- (void)addTrailPoint:(TrailPoint *)point;

@end
